name = "fgof-expect"
version = "0.1.0"
license = "MIT"
author = "FortranGoingOnForty"
maintainer = "FortranGoingOnForty"
copyright = "2026"
description = "Expect-style PTY automation for modern Fortran"

[build]
auto-executables = false
auto-tests = true
auto-examples = true

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
fgof-pty = { git = "https://github.com/FortranGoingOnForty/fgof-pty.git", tag = "v0.1.0" }
